### ISSUE TITLE
Cluster(ing) ?

### ISSUE THREAD

**Issue by ddorian** [hntd187/Toshi#4]
Hey,

Assuming you want to build a better/faster elasticsearch alternative. What do you think about building this on top of `tikv`?

This way you get replication, sharding, commitlog, transactions,raft,grpc,backups,multi-datacenter,native-local-functions etc for ~free. 

At a minimum, you can replace the `sstable` of `rocksdb` to store a `tantivy segment`. 
Doing crud you check on commitlog then on the `segment`, while doing search you just check on sstables.  You can replace the `memtable` with another `tantity segment` to enable real-time querying without refresh. (refreshing would translate+persist the `memtable` memory-segment to `sstable` disk-segment. 

Using grpc maybe even be better than http/json.

Makes sense ? Compared to do-it-yourself ?

ps: best/extreme scenario would be to build it on top of seastar-framework but it's probably too much work compared to above.

**Comment by hntd187** [comment]
I'm not sure how I would accomplish that. Are you suggesting I fork tikv to use tantivy segments instead of the rocksdb they have on the backend? I was considering using their raft implementation for when I get to the cluster orchestration, but beyond that, I'm not sure how much of this would be directly usable since tikv is infrastructure, I don't think they provide a library to do this kind of thing unless I'm missing something?

**Comment by ddorian** [comment]
As a minimum example without much forking you could do::::
1. implement tantivy as a custom index on tidb
2. using coprocessors to implement search and adding custom function on query-language to do the search like `select search("search_string_query") from table;`.

You'll need to fork, I don't think it's that easy customizable/pluggable.
I was suggesting to still use rocksdb, but use a custom memtable/sstable which would be a tantivy index.

**Comment by hntd187** [comment]
tidb is written in go though, right? I think this is a bit too heavy at this point to consider. I'll probably want to use these projects as reference and inspiration for my own implementation, but it would seem very heavy to support and I don't necessarily understand how these 2 would fit together because I am not really trying to make or implement an SQL like syntax on this.

**Comment by ddorian** [comment]
tidb yes, tikv in rust.

The idea is that elasticsearch started distributed from start. It'll gonna be hard to start from single node and then change later. And using tikv looked like a great way to start for me.
